"use strict";
// environment config goes here
module.exports = {
    RING_REFRESH_TOKEN: 'eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2NTkzMjI3ODMsImlzcyI6IlJpbmdPYXV0aFNlcnZpY2UtcHJvZDp1cy1lYXN0LTE6ZjEwMmRlOWIiLCJyZWZyZXNoX2NpZCI6InJpbmdfb2ZmaWNpYWxfYW5kcm9pZCIsInJlZnJlc2hfc2NvcGVzIjpbImNsaWVudCJdLCJyZWZyZXNoX3VzZXJfaWQiOjYxODYyMDAxLCJybmQiOiJoMDMxZWJacFZXQXRqZyIsInNlc3Npb25faWQiOiIwNjYyMzFhMy03ZGQ5LTQ3MDUtYTM3MC1jZjUxYTgwYTM2ZDgiLCJ0eXBlIjoicmVmcmVzaC10b2tlbiJ9.HdHIT87ErwokQiRKvXCW5no_9ykPnOLz-jsllTadlFoSBu1Scem6jR8eGUVHk-jsy98Q7idz9yvC5IqZCjO5sA',
};
